/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.umg;

import static com.umg.service.Constant.COLAS;
import com.umg.service.QueueService;
import com.umg.service.StackService;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Nestor Gaitan
 */
public class WorkSpace extends javax.swing.JFrame {

    /**
     * Creates new form WorkSpace
     */
    private String option = "";
    private QueueService queueService = new QueueService();
    private StackService stackService = new StackService();
    private ShowInformation information = new ShowInformation();

    public WorkSpace() {
        initComponents();
    }

    public void start(String option) {
        this.option = option;
        this.jLabel1.setText("trabajando con " + option);
        if (COLAS.equals(option)) {
            information.getComponentShow().setListData(queueService.getVector());
        } else {
            setStack(stackService.getVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbuttonIngresar = new javax.swing.JButton();
        jbuttonAtender = new javax.swing.JButton();
        JbuttonVisualizar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("trabajando con");

        jbuttonIngresar.setText("Ingresar Datos");
        jbuttonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonIngresarActionPerformed(evt);
            }
        });

        jbuttonAtender.setText("Atender");
        jbuttonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAtenderActionPerformed(evt);
            }
        });

        JbuttonVisualizar.setText("Visualizar");
        JbuttonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbuttonIngresar)
                        .addGap(30, 30, 30)
                        .addComponent(jbuttonAtender)
                        .addGap(32, 32, 32)
                        .addComponent(JbuttonVisualizar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonIngresar)
                    .addComponent(jbuttonAtender)
                    .addComponent(JbuttonVisualizar))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonIngresarActionPerformed
        if (COLAS.equals(option)) {
            registerQueue();
        } else {
            registerStack();
        }

    }//GEN-LAST:event_jbuttonIngresarActionPerformed

    private void registerQueue() {
        final int size = queueService.getVector().size() + 1;
        if (size > 20) {
            JOptionPane.showConfirmDialog(this, "numero maximo de tickets alcanzados", "limite excedido", JOptionPane.ERROR_MESSAGE);
        }
        final String value = JOptionPane.showInputDialog(this, "ingrese el tiket numero " + size, "Ingresar", JOptionPane.CLOSED_OPTION);
        queueService.getVector().add(value);
        information.getComponentShow().setListData(queueService.getVector());

    }

    private void registerStack() {
        final int size = stackService.getVector().size();
        final int index = 20 - size;
        if (size > 19) {
            JOptionPane.showConfirmDialog(this, "numero maximo de tickets alcanzados", "limite excedido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        final String value = JOptionPane.showInputDialog(this, "ingrese el tiket numero " + index, "Ingresar", JOptionPane.CLOSED_OPTION);
        stackService.getVector().add(value);
        setStack(stackService.getVector());
    }

    private void jbuttonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAtenderActionPerformed
        if (COLAS.equals(option)) {
            getTicketQueue();
        } else {
            getTicketStack();
        }
    }//GEN-LAST:event_jbuttonAtenderActionPerformed

    private void JbuttonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonVisualizarActionPerformed

        if (COLAS.equals(option)) {
            showQueues();
        } else {
            showStack();
        }


    }//GEN-LAST:event_JbuttonVisualizarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void showQueues() {
        information.getComponentShow().setListData(queueService.getVector());
        information.setLocationRelativeTo(null);
        information.setVisible(true);
    }

    private void showStack() {
        setStack(stackService.getVector());
        information.setLocationRelativeTo(null);
        information.setVisible(true);
    }

    private void getTicketQueue() {
        final int size = queueService.getVector().size();
        final int index = 21 - size;

        if (size == 0) {
            JOptionPane.showConfirmDialog(this, "sin ticket pendientes", "sin tickets", JOptionPane.CLOSED_OPTION);
            return;
        }

        Object ticket = queueService.getVector().firstElement();
        JOptionPane.showConfirmDialog(this, "atendiendo: " + ticket, "atender ticket", JOptionPane.CLOSED_OPTION);
        queueService.getVector().remove(0);
        information.getComponentShow().setListData(queueService.getVector());

    }

    private void getTicketStack() {
        final int size = stackService.getVector().size();
        final int index = size - 1;

        if (size == 0) {
            JOptionPane.showConfirmDialog(this, "sin ticket pendientes", "sin tickets", JOptionPane.CLOSED_OPTION);
            return;
        }

        Object ticket = stackService.getVector().get(index);
        JOptionPane.showConfirmDialog(this, "atendiendo: " + ticket, "atender ticket", JOptionPane.CLOSED_OPTION);
        stackService.getVector().remove(index);
        setStack(stackService.getVector());

    }

    private void setStack(Vector vector) {
        int size = vector.size();
        Vector order = new Vector();
        for (int i = size; i >= 1; i--) {
            order.add(vector.get(i - 1));
        }
        information.getComponentShow().setListData(order);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkSpace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkSpace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkSpace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkSpace.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkSpace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbuttonAtender;
    private javax.swing.JButton jbuttonIngresar;
    // End of variables declaration//GEN-END:variables
}
